# This file uses environment variables as properties and 
# can be used in container environments.

spring:
  datasource:
    url: ${VEO_DATASOURCE_URL}
    username: ${VEO_DATASOURCE_USERNAME}
    password: ${VEO_DATASOURCE_PASSWORD}
    driver-class-name: ${VEO_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    database-platform: ${VEO_JPA_DATABASE_PLATFORM}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  ${VEO_OAUTH2_ISSUER_URI}
          jwk-set-uri: ${VEO_OAUTH2_JWK_URI}
