server:
  port: 8070

veo:
  basedir: ${user.home}/.local/share/veo
  cors:
    origins: <ALLOWED_ORIGIN1>, <ALLOWED_ORIGIN2>
  # Salt for hashing the ETags, enter a 10 random characters
  # etag:
    # salt:
  logging:
    properties: 'spring.datasource.url,spring.jpa.database-platform'

spring:
  data:
    rest:
      detection-strategy: annotated
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
    ## Turn OSIV off - only the business layer decides the fetching strategy for a particular use case:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          # execute statements in batches:
          batch_size: 30
          # batch updates and deletes for entities that have a @Version property:
          batch_versioned_data: true
        query:
          # prevent in-memory pagination when join fetching collections:
          fail_on_pagination_over_collection_fetch: true
          # pad 'IN'-clauses to next power of 2 to improve statement caching:
          in_clause_parameter_padding: true
        connection:
          # removes the necessity to acquire the db connection at the beginning of each
          # transaction to check the autocommit status:
          # IMPORTANT: hikari.auto-commit=false must be set as well
          provider_disables_autocommit: true
  datasource:
    hikari:
      auto-commit: false

  security:
    oauth2:
      resourceserver:
        jwt:
          ## Auth Server OIDC Discovery location, i.e.: http://<AUTHSERVER>/auth/realms/<REALM>
          issuer-uri: http://<AUTHSERVER>/auth/realms/<REALM>
          ## Auth Server private key location, i.e.: http://<AUTHSERVER>/auth/realms/<REALM>/protocol/openid-connect/certs
          jwk-set-uri: http://<AUTHSERVER>/auth/realms/<REALM>/protocol/openid-connect/certs

## Change log level for different packages:
#logging:
#  level:
#    org.springframework: DEBUG

